apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-test
  template:
    metadata:
      labels:
        app: frontend-test
    spec:
      containers:
        - name: frontend-test
          image: ghcr.io/bastiang03/frontend:latest
          ports:
            - containerPort: 8080