apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-test
  template:
    metadata:
      labels:
        app: backend-test
    spec:
      containers:
        - name: backend
          image: ghcr.io/bastiang03/backend:latest
          ports:
            - containerPort: 8080