name: Go Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v5
      - name: Build
        run: .backend/ go build
      - name: Run tests
        run: go test ./frontend
