name: Go Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v5
      - name: Build backend
        run: cd backend && go build
      - name: Build frontend
        run: cd frontend && go build
      - name: Test frontend
        run: cd frontend && go test
