name: Go Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v5
      - name: Build backend
        run: cd backend && go build
      - name: Build frontend
        run: cd frontend && go build
      - name: Test frontend
        run: cd frontend && go test
  docker-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build-docker-image backend
        run: cd backend && docker build -t ghcr.io/bastiang03/backend:latest .
      - name: push docker image backend
        run: docker push ghcr.io/bastiang03/backend:latest

      - name: build docker image frontend
        run: cd frontend && docker build -t ghcr.io/bastiang03/frontend:latest .
      - name: push docker image frontend
        run: docker push ghcr.io/bastiang03/frontend:latest
